### ISSUE TITLE
List Widget

### ISSUE THREAD

**Issue by evripidesk** [fasky-software/flutter_widgetkit#1]
Hello

Excellent package! I tired your example and is working perfectly 

Now the question is how we can send a list of data and how we can change the code in swift?

Thanks
Evripides

**Comment by tomLadder** [comment]
Thanks. You can store any data (String, Bool, Number...) you want into the UserDefaults. In your case you would JSON stringify your list of data (Array) and decode it on the other end :)

**Comment by evripidesk** [comment]
Thank you for your answer
Yes but do you have any sample with array how swift can handle it, I dont know swift , how can I change your example to handle the array in swift 👍

**Comment by tomLadder** [comment]
@evripidesk Please have a look at some internet resources. There should be numerous articles/postings on how to deserialize "more complicated" sturctures with SwiftUI.
