### ISSUE TITLE
Update Widget invalid

### ISSUE THREAD

**Issue by iworkcloud** [fasky-software/flutter_widgetkit#11]
ios 14.6 iphoneXR  Update Widget invalid！No Data found! Go to the Flutter App

**Comment by josephshepin** [comment]
I spent a long time on this issue, so hopefully this will help others. 

- you must set a "app group" for both the runner and the widget. (Both tabs shown below)
<img width="424" alt="Screen Shot 2021-11-19 at 11 23 53 PM" src="https://user-images.githubusercontent.com/31457361/142715513-ff84f92c-07c5-4df8-9f1e-d209c36aa9da.png">

- make sure the "key" is constant across both the swift file and the dart file. I used "widgetData" as mine, but the example did have them mismatched, so be careful there.

**Comment by iworkcloud** [comment]
thank you!
