### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by evripidesk** [fasky-software/flutter_widgetkit#2]
hello

When I am trying to build for ios I get the following error 

`Automatically signing iOS for device deployment using specified development team
in Xcode project: TYR8M23SD7
Running Xcode build...                                                  
Xcode build done.                                            8.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wi
    dgetkit-1.0.0/ios/Classes/SwiftFlutterWidgetkitPlugin.swift:15:9: error:
    cannot find 'WidgetCenter' in scope
            WidgetCenter.shared.reloadAllTimelines()
            ^~~~~~~~~~~~
    /Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wi
    dgetkit-1.0.0/ios/Classes/SwiftFlutterWidgetkitPlugin.swift:23:11: error:
    cannot find 'WidgetCenter' in scope
              WidgetCenter.shared.reloadTimelines(ofKind: ofKind)
              ^~~~~~~~~~~~
    /Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wi
    dgetkit-1.0.0/ios/Classes/SwiftFlutterWidgetkitPlugin.swift:58:36: warning:
    conditional cast from 'Any?' to 'Any' always succeeds
             let value = args["value"] as? Any {
                                       ^
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    8.0, but the range of supported deployment target versions is 9.0 to
    14.1.99. (in target 'flutter_widgetkit' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    8.0, but the range of supported deployment target versions is 9.0 to
    14.1.99. (in target 'Flutter' from project 'Pods')

It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for device.`

**Comment by evripidesk** [comment]
any news with this?

**Comment by tomLadder** [comment]
Hey @evripidesk.
Does the error occur when you want to create a release/archive build?

**Comment by evripidesk** [comment]
Hello

when I create a release , when I am running the command flutter build ios

**Comment by tomLadder** [comment]
Ok thanks for the info. I will have a look at it @evripidesk

**Comment by tomLadder** [comment]
@evripidesk Just released version 1.0.1 🕺, this should fix your problem :)

**Comment by evripidesk** [comment]
Perfect that did the trick 
Thank you
