### ISSUE TITLE
deleteItem / removeItem missing

### ISSUE THREAD

**Issue by Ahmadre** [fasky-software/flutter_widgetkit#5]
At first: Thank you soo much for this awesome Plugin! Very good job!

But I am missing the remove/delete function in Flutter. I can get and set items, but not deleting a key/value pair from UserDefaults.

Is that possible?

best regards
Rebar :)

**Comment by tomLadder** [comment]
Hey @Ahmadre 

Thanks for the feedback. You are right, that would be a useful feature. I will have a look at it 👍

**Comment by Ahmadre** [comment]
I already created a removeItem impl. and will create a PR soon 👍 
I'm testing it.

**Comment by tomLadder** [comment]
Great, looking forward to

**Comment by Ahmadre** [comment]
@tomLadder I would appreciate it if you can have a look in here: https://github.com/fasky-software/flutter_widgetkit/pull/6
