### ISSUE TITLE
Works in debug mode, does not in production

### ISSUE THREAD

**Issue by majindageta** [fasky-software/flutter_widgetkit#7]
Hello there, 
this is very strange and don't really know why.

The library works perfectly in debug mode (running in simulator or on an iphone)
when sending the app to the apple store via testflight nothing is returned from the library.

The appgroup in my app was already present before using this library.

Using the latest library version and latest xcode on Big Sur.

````
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0.1 20B50, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[!] Connected device
    ! No devices available
```

**Comment by majindageta** [comment]
Hello, sorry for opening this issue.
I've not tested yet but i saw that the "entitlements" with the "app group" is marked as "debug" instead of release.

I really think is only this.

**Comment by tomLadder** [comment]
@majindageta No problem. Glad you solved it 👍🏻
