### ISSUE TITLE
Update widget background

### ISSUE THREAD

**Issue by evripidesk** [fasky-software/flutter_widgetkit#8]
Hello

Can we update the widget in the backround (without opening app)

I tried with workmanager but is not working

**Comment by Ahmadre** [comment]
> Hello
> 
> 
> 
> Can we update the widget in the backround (without opening app)
> 
> 
> 
> I tried with workmanager but is not working 

This issue isn't related to this plugin. You need to have a deeper look into SwiftUI. Make your own safe with the types of updates that can be made in the Widgets :).
